### ISSUE TITLE
Required fields in Proto

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-ref-system#1]
Shouldn't we be adding `required` to the SharedStreets Protobuf schema?

https://github.com/sharedstreets/sharedstreets-ref-system/blob/master/proto/sharedstreets.proto#L120-L130

```proto
message SharedStreetsIntersection {

  string id = 1;
  uint64 nodeId = 2;
  float lat = 3;
  float lon = 4;

  repeated string inboundReferenceIds = 5;
  repeated string outboundReferenceIds = 6;

}
```

Are all of these fields required? If so, shouldn't we be added `required` or `optional` for each variable.

### Could translates to:

```proto
message SharedStreetsIntersection {

  required string id = 1;
  required uint64 nodeId = 2;
  required float lat = 3;
  required float lon = 4;

  repeated string inboundReferenceIds = 5;
  repeated string outboundReferenceIds = 6;

}
```

> Is `nodeId` optional or required?

**Comment by kpwebb** [comment]
Required was dropped in proto3 so all fields are optional.

https://stackoverflow.com/questions/31801257/why-required-and-optional-is-removed-in-protocol-buffers-3

**Comment by DenisCarriere** [comment]
👍 Learn something new every day 😄
