### ISSUE TITLE
Issues reproducing intersectionId based on PBF sample data

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-ref-system#10]
## Issues reproducing `intersectionId` based on PBF sample data

Trying to generate `intersectionId` from this sample data.

[nyc/11-602-769.intersection.pbf](https://github.com/sharedstreets/sharedstreets-ref-system/blob/master/sample_data/nyc/11-602-769.intersection.pbf)

[11-602-769.intersection.json](https://github.com/sharedstreets/sharedstreets-pbf/blob/master/test/out/11-602-769.intersection.json#L2-L15)

```json
{
  "id": "8037a9444353cd7dd3f58d9a436f2537",
  "nodeId": "42436088",
  "lat": 40.72600173950195,
  "lon": -74.00909423828125,
  "inboundReferenceIds": [
    "4ca0b3417550efb8dc1224883c15c23d",
    "72ec925a20ac3a7f5935c284234d1e3e"
  ],
  "outboundReferenceIds": [
    "a2073f60b719681019f67db50839dae4",
    "1482d512d1d9fff37f34fed597a6912b"
  ]
}
```

## Javascript Example

```js
const sharedstreets = require('sharedstreets')

// Intersection Point [x, y]
const pt = [-74.00909423828125, 40.72600173950195]

const id = sharedstreets.intersectionId(pt)
const message = sharedstreets.intersectionMessage(pt)
```
## Expected Value

Value pulled from the sample data generated by (Java builder)

```
// message => ???
// id => "8037a9444353cd7dd3f58d9a436f2537"
```

## Actual Value

Value generated via Javascript

```
// message => "Intersection -74.009094 40.726002"
// id => "6f1c08066370129f2f429f3c20f9e151"
```

@kpwebb Could we include more test examples for generating Unique Ids in your Java builder.

https://github.com/sharedstreets/sharedstreets-builder/blob/master/src/test/java/io/sharedstreets/tools/builder/util/UniqueIdTest.java

**Comment by DenisCarriere** [comment]
Also having an issue with `geometryId` for the following:

https://github.com/sharedstreets/sharedstreets-pbf/blob/master/test/out/11-602-770.geometry.json#L309-L326

**[`nyc_test.pbf`](https://github.com/sharedstreets/sharedstreets-builder/blob/master/data/nyc_test.pbf) sample data**

```json
{
  "id": "47a4d383cb1d805614d9afadc1de36fa",
  "fromIntersectionId": "2f512700e8c2b26ce3568c49b693db51",
  "toIntersectionId": "1b3703280d75efd84475cca6450cc3bf",
  "forwardReferenceId": "8f4e865b51eb64bbac33b68e8fe30971",
  "backReferenceId": "3792db293c350dfa08cfc68343d7697f",
  "roadClass": "Service",
  "latlons": [
    40.63066101074219,
    -74.00613403320312,
    40.630714416503906,
    -74.00608825683594,
    40.630924224853516,
    -74.0058822631836,
    40.630977630615234,
    -74.0059814453125
  ]
}
```

## Javascript example

```js
const coords = sharedstreets.latlonsToCoords([
  40.63066101074219,
  -74.00613403320312,
  40.630714416503906,
  -74.00608825683594,
  40.630924224853516,
  -74.0058822631836,
  40.630977630615234,
  -74.0059814453125
]);
const message = sharedstreets.geometryMessage(coords);
const id = sharedstreets.geometryId(coords);
```

## Expected (from PBF => JSON sample data)

```js
message // => ???
id // => '47a4d383cb1d805614d9afadc1de36fa'
```

## Actual (generated via Javascript)

```js
message // => 'Geometry -74.006134 40.630661 -74.006088 40.630714 -74.005882 40.630924 -74.005981 40.630978'
id // => 'ff187aa3f332e2421ac9aa094aae592f'
```

@kpwebb Is there a way you can confirm the `Message` output string in a Java unit test?

**Comment by kpwebb** [comment]
@DenisCarriere just updated tests and discovered this is an x/y vs lat/lon ordering issue. 
 
[edited -- need to confirm which way the JS and java libs are currently ordering]

**Comment by kpwebb** [comment]
Also, let's make the JS version the reference implementation since it is simpler and easier to read/use. We could make a simple id tester app (or even a simple web service) that lets folks push in sample data and get references back out to integrate with testing suites in other apps (e.g. the java app could test against the JS app).

**Comment by kpwebb** [comment]
Ok, I was totally wrong about this. It's actually a float precision bug. We're storing lat/lon as floats in PBF but working with them as doubles in Java. 

Here's the internal pre export feature in Java:
sharedStreetsIntersection.point = {Point@789} "{"x":-74.0090917,"y":40.7260025}"
Results in ID "Intersection -74.009092 40.726003" -> 8037a9444353cd7dd3f58d9a436f2537

Here's the same feature after generating and reimporting from PBF;
sharedStreetsIntersectionPostPBF.point = {Point@1198} "{"x":-74.00909423828125,"y":40.72600173950195}"
Results in ID "Intersection -74.009094 40.726002" -> 6f1c08066370129f2f429f3c20f9e151

Two options to fix this:

1) Switch protobuf format to use doubles
2) Round values internally to float precision before calculating Ids.

I'm leaning toward #2 -- I don't think we need  double precision and don't want to bump file size to from 32-bit to 64-bit values if we don't actually need the precision. But I also need to confirm that we can get six-decimal precision with a float.

**Comment by kpwebb** [comment]
Hmm, so this is trickier than I'd hoped. Floats don't get us +/- 0.000001, more like +/- 0.00001 for values > 100 or < -100, which means something along the lines of +/- 5 meters at the equator. 

That's not good enough. 

It works for references, but it means that downstream linear features can't be more precise. I think we want to target a spatial resolution of > 1m. Many data sets won't achieve this, but it's possible with OTS GSP to get ~1cm resolution and would be a missed opportunity to build the standard at ~5m precision.

I think we should still shoot for sixth-decimal place for the reference (per the current hash format) but change the PBF to store double precision values.

**Comment by kpwebb** [comment]
bumped to double precision with [2de2d91](https://github.com/sharedstreets/sharedstreets-ref-system/commit/2de2d91080f65b5de434808c6b63793f5694494a) and cleaned up ordering, geometries now encoded as lon,lat to match other ordering.

**Comment by kpwebb** [comment]
went ahead and made this change. one alternative is to use [OSM PBF lat lon encoding](https://wiki.openstreetmap.org/wiki/PBF_Format#Definition_of_OSMData_fileblock) but not sure it is worth the added complexity.

**Comment by DenisCarriere** [comment]
> Floats don't get us +/- 0.000001, more like +/- 0.00001 for values > 100 or < -100, which means something along the lines of +/- 5 meters at the equator.

If we can at least match the GeoJSON coordinates precision to 6 positions, (+/- 0.000001) which is +/- 10cm precision, that would be plenty enough for high precision implementation.

https://tools.ietf.org/html/rfc7946#section-11.2

> bumped to double precision with 2de2d91 and cleaned up ordering, geometries now encoded as lon,lat to match other ordering.

👍 Nice

> one alternative is to use OSM PBF lat lon encoding but not sure it is worth the added complexity.

I think using paired `lonlats` is fine, no need to make it overly complicated to define LineString coordinates for Geometry.

**Comment by DenisCarriere** [comment]
FYI: Geometry Id's & Intersection Id's both work at 100% between Javascript & Java 👍
