### ISSUE TITLE
Packed latlons Geometry Proto

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-ref-system#6]
Seems like the `latlons` Proto variable should contain `[ packed = true ]`.

Mapbox Vector Tile schema uses this as well: https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto

Should look something like this:

```proto
message SharedStreetsGeometry {

    required string id = 1;

    required string fromIntersectionId = 2;
    required string toIntersectionId = 3;
    optional string forwardReferenceId = 4;
    optional string backReferenceId = 5;

    optional RoadClass roadClass = 6;
    repeated float latlons = 7 [ packed = true ]; // interleaved lat/lon pairs in sequence

}
```

**Comment by kpwebb** [comment]
If we stick with proto3, packed=true is the default for repeated fields. So not sure this change is needed. 

https://developers.google.com/protocol-buffers/docs/encoding

**Comment by DenisCarriere** [comment]
👍 Seems like Mapbox's Protobuf syntax comes from Proto Version 2, I'll read up on Google's Version 3 before making more syntax comments 🤕
